# Generated by Django 3.0.8 on 2020-07-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(verbose_name='transaction date'),
        ),
    ]
