# Generated by Django 3.0.8 on 2020-07-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_transactions_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
